# Generated by Django 4.0.4 on 2022-06-05 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 2, 54, 14, 598681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 2, 54, 14, 598998, tzinfo=utc)),
        ),
    ]
