# Generated by Django 4.0.4 on 2022-06-05 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_create_time_alter_todo_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
