# Generated by Django 4.0.4 on 2022-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_create_time_alter_todo_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='limit_date',
            field=models.DateTimeField(),
        ),
    ]
